In [1]:
# Import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Cek File alert Kota Bandung
Cek file aggregate_alerts_Kota Bandung.csv

In [2]:
df_alerts_kota_bandung = pd.read_csv(r'..\Data\aggregate_alerts_Kota Bandung.csv')

In [3]:
df_alerts_kota_bandung.sample(5)

,id,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,type,avg_location,total_records,date
21121,6133963,2022-08-18 18:00:00.000,32.73,KOTA BANDUNG,Jalan Aceh,JAM,"[107.616403, -6.90951]",3,2022-08-18
19655,6121033,2022-08-15 13:00:00.000,32.73,KOTA BANDUNG,Batununggal Jelita 1,WEATHERHAZARD,"[107.634912, -6.9559050000000004]",29,2022-08-15
16735,6092776,2022-08-09 07:00:00.000,32.73,KOTA BANDUNG,Terusan Jakarta,JAM,"[107.655724, -6.912574]",2,2022-08-09
19369,6116945,2022-08-14 18:00:00.000,32.73,KOTA BANDUNG,Ciumbuleuit,JAM,"[107.60372999999997, -6.878513999999997]",26,2022-08-14
17415,6097504,2022-08-10 21:00:00.000,32.73,KOTA BANDUNG,N11 Flyover Kopo-Cibaduyut,ROAD_CLOSED,"[107.59261600000008, -6.9461275]",120,2022-08-10

In [4]:
df_alerts_kota_bandung.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30385 entries, 0 to 30384
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         30385 non-null  int64
 1   time                       30385 non-null  object
 2   kemendagri_kabupaten_kode  30385 non-null  float64
 3   kemendagri_kabupaten_nama  30385 non-null  object
 4   street                     28496 non-null  object
 5   type                       30385 non-null  object
 6   avg_location               30385 non-null  object
 7   total_records              30385 non-null  int64
 8   date                       30385 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 2.1+ MB

In [5]:
df_alerts_kota_bandung.isnull().sum()

id                              0
time                            0
kemendagri_kabupaten_kode       0
kemendagri_kabupaten_nama       0
street                       1889
type                            0
avg_location                    0
total_records                   0
date                            0
dtype: int64

In [6]:
df_alerts_kota_bandung[df_alerts_kota_bandung['avg_location'] == '[107.69066199999999, -6.958103499999996]']

,id,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,type,avg_location,total_records,date
7,5930358,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-06
16,5930374,2022-07-06 02:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-06
26,5930382,2022-07-06 03:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-06
148,5930499,2022-07-06 10:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-06
171,5930523,2022-07-06 11:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-06
373,5930766,2022-07-06 18:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-06
480,5930831,2022-07-06 20:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-06
575,5934911,2022-07-07 08:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-07
622,5934966,2022-07-07 11:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",116,2022-07-07
833,5935158,2022-07-07 17:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-07
908,5935234,2022-07-07 19:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-07
1033,5939754,2022-07-08 09:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",100,2022-07-08
1067,5939776,2022-07-08 10:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-08
1172,5939894,2022-07-08 14:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-08
1506,5940242,2022-07-08 21:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-08
1549,5940258,2022-07-08 22:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-08
1642,5944358,2022-07-09 08:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",122,2022-07-09
1657,5944373,2022-07-09 09:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-09
1797,5944513,2022-07-09 14:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-09
1867,5944583,2022-07-09 16:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-09
1894,5944610,2022-07-09 17:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-09
1946,5944662,2022-07-09 19:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-09
1968,5944684,2022-07-09 20:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-09
1987,5944703,2022-07-09 21:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",122,2022-07-09
1999,5944715,2022-07-09 22:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-09
2074,5947921,2022-07-10 07:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-10
2095,5947942,2022-07-10 09:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-10
2107,5947954,2022-07-10 10:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",122,2022-07-10
2134,5947981,2022-07-10 12:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-10
2173,5948020,2022-07-10 14:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-10
2305,5948152,2022-07-10 22:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-10
2314,5948161,2022-07-10 23:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-10
2322,5951756,2022-07-11 00:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-11
2329,5951763,2022-07-11 01:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",122,2022-07-11
2382,5951828,2022-07-11 08:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-11
2412,5951864,2022-07-11 10:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-11
2540,5951974,2022-07-11 15:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-11
2649,5952083,2022-07-11 20:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-11
2741,5956346,2022-07-12 08:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-12
2759,5956366,2022-07-12 09:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-12
2782,5956387,2022-07-12 10:00:00.000,32.73,KOTA BANDUNG,NaN,ROAD_CLOSED,"[107.69066199999999, -6.958103499999996]",120,2022-07-12

In [7]:
df_alerts_kota_bandung.head()

,id,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,type,avg_location,total_records,date
0,5930351,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Batununggal Indah 2,WEATHERHAZARD,"[107.62634049999998, -6.962361499999998]",120,2022-07-06
1,5930352,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Cibaduyut Raya,ROAD_CLOSED,"[107.59526000000004, -6.9472129999999925]",60,2022-07-06
2,5930353,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Gerbang Tol Gede Bage,ROAD_CLOSED,"[107.69057999999981, -6.959956500000006]",120,2022-07-06
3,5930354,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Jenderal Ahmad Yani,WEATHERHAZARD,"[107.65976500000006, -6.902228999999994]",60,2022-07-06
4,5930355,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,KH Wahid Hasyim,ROAD_CLOSED,"[107.58966274999973, -6.945608999999994]",240,2022-07-06

## Cek File Median Irregularities Kota Bandung
Cek file aggregate_median_irregularities_Kota Bandung.csv

In [8]:
df_median_irregularities_kota_bandung = pd.read_csv(r'..\Data\aggregate_median_irregularities_Kota Bandung.csv')

In [9]:
df_median_irregularities_kota_bandung.head(5)

,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,jam_level,median_length,median_delay_seconds,median_regular_speed,total_records,cause_type,median_seconds,median_speed,date,median_jam_level,id,geometry
0,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,Terusan Buah Batu,4,1922.0,657.0,15.770000,13,NaN,844.0,7.51,2022-07-06,4.0,1492848,"MULTILINESTRING ((107.638019 -6.965016, 107.63..."
1,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,Jenderal AH Nasution,3,1819.0,421.0,17.939999,2,NaN,572.0,11.60,2022-07-06,3.0,1492844,"LINESTRING (107.678021 -6.904799, 107.677631 -..."
2,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,Jenderal AH Nasution,4,1064.0,586.0,14.520000,11,NaN,675.0,6.14,2022-07-06,4.0,1492845,"MULTILINESTRING ((107.659819 -6.902242, 107.66..."
3,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,N11 Soekarno-Hatta,4,919.0,558.5,15.095000,20,NaN,632.0,4.97,2022-07-06,4.0,1492846,"MULTILINESTRING ((107.641468 -6.945648, 107.64..."
4,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,Terusan Buah Batu,3,2024.0,599.0,15.830000,1,NaN,786.0,9.26,2022-07-06,3.0,1492847,"LINESTRING (107.638019 -6.965016, 107.638179 -..."

In [10]:
df_median_irregularities_kota_bandung.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11281 entries, 0 to 11280
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   time                       11281 non-null  object
 1   kemendagri_kabupaten_kode  11281 non-null  float64
 2   kemendagri_kabupaten_nama  11281 non-null  object
 3   street                     11279 non-null  object
 4   jam_level                  11281 non-null  int64
 5   median_length              11281 non-null  float64
 6   median_delay_seconds       11281 non-null  float64
 7   median_regular_speed       11281 non-null  float64
 8   total_records              11281 non-null  int64
 9   cause_type                 0 non-null      float64
 10  median_seconds             11281 non-null  float64
 11  median_speed               11281 non-null  float64
 12  date                       11281 non-null  object
 13  median_jam_level           11281 non-null  float64
 14  id                         11281 non-null  int64
 15  geometry                   11281 non-null  object
dtypes: float64(8), int64(3), object(5)
memory usage: 1.4+ MB

In [11]:
df_median_irregularities_kota_bandung.head()

,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,jam_level,median_length,median_delay_seconds,median_regular_speed,total_records,cause_type,median_seconds,median_speed,date,median_jam_level,id,geometry
0,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,Terusan Buah Batu,4,1922.0,657.0,15.770000,13,NaN,844.0,7.51,2022-07-06,4.0,1492848,"MULTILINESTRING ((107.638019 -6.965016, 107.63..."
1,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,Jenderal AH Nasution,3,1819.0,421.0,17.939999,2,NaN,572.0,11.60,2022-07-06,3.0,1492844,"LINESTRING (107.678021 -6.904799, 107.677631 -..."
2,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,Jenderal AH Nasution,4,1064.0,586.0,14.520000,11,NaN,675.0,6.14,2022-07-06,4.0,1492845,"MULTILINESTRING ((107.659819 -6.902242, 107.66..."
3,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,N11 Soekarno-Hatta,4,919.0,558.5,15.095000,20,NaN,632.0,4.97,2022-07-06,4.0,1492846,"MULTILINESTRING ((107.641468 -6.945648, 107.64..."
4,2022-07-06 07:00:00.000,32.73,KOTA BANDUNG,Terusan Buah Batu,3,2024.0,599.0,15.830000,1,NaN,786.0,9.26,2022-07-06,3.0,1492847,"LINESTRING (107.638019 -6.965016, 107.638179 -..."

## Cek File Median Jams Kota Bandung
Cek file aggregate_median_Jams_Kota Bandung.csv

In [12]:
df_median_jams_kota_bandung = pd.read_csv(r'..\Data\aggregate_median_jams_Kota Bandung_fixed.csv')

In [13]:
df_median_jams_kota_bandung.sample(5)

,Unnamed: 0,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,level,median_length,median_delay,median_speed_kmh,total_records,id,date,median_level,geometry
143358,125491,2022-08-03 15:00:00.000,32.73,KOTA BANDUNG,Gardujati,3,418.0,131.0,7.92,57,35274738,2022-08-03,3.0,"MULTILINESTRING ((107.598343 -6.920117, 107.59..."
228404,78526,2022-08-21 13:00:00.000,32.73,KOTA BANDUNG,Cikutra,2,605.5,80.0,13.78,16,36374815,2022-08-21,2.0,"MULTILINESTRING ((107.635449 -6.892753, 107.63..."
45966,28099,2022-07-16 09:00:00.000,32.73,KOTA BANDUNG,Surapati,2,1370.0,87.0,22.43,43,34108010,2022-07-16,2.0,"MULTILINESTRING ((107.624447 -6.89923, 107.623..."
244439,94561,2022-08-25 06:00:00.000,32.73,KOTA BANDUNG,Surapati,4,937.0,425.0,6.51,1,36581719,2022-08-25,4.0,"LINESTRING (107.631757 -6.898513, 107.631284 -..."
5605,462,2022-07-07 08:00:00.000,32.73,KOTA BANDUNG,Jenderal AH Nasution,3,1395.0,156.0,17.76,25,33536947,2022-07-07,3.0,"MULTILINESTRING ((107.675685 -6.904687, 107.67..."

In [14]:
df_median_jams_kota_bandung.head()

,Unnamed: 0,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,level,median_length,median_delay,median_speed_kmh,total_records,id,date,median_level,geometry
0,0,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Jenderal Ahmad Yani,4,428.0,201.5,6.29,14,33471439,2022-07-06,4.0,"MULTILINESTRING ((107.622869 -6.919558, 107.62..."
1,1,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Cibaduyut Raya,5,24.0,-1.0,0.00,60,33471432,2022-07-06,5.0,"MULTILINESTRING ((107.59526 -6.947213, 107.595..."
2,2,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Cidurian Selatan,2,531.0,101.5,9.07,2,33471433,2022-07-06,2.0,"LINESTRING (107.652971 -6.940132, 107.653181 -..."
3,3,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Dr Setiabudi,1,919.0,61.0,20.42,2,33471434,2022-07-06,1.0,"LINESTRING (107.593922 -6.866493, 107.5939 -6...."
4,4,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Gerbang Tol Gede Bage,5,318.5,-1.0,0.00,120,33471435,2022-07-06,5.0,"MULTILINESTRING ((107.690448 -6.961397, 107.69..."

In [15]:
df_median_jams_kota_bandung = df_median_jams_kota_bandung.drop('Unnamed: 0',1)
df_median_jams_kota_bandung.head()

C:\Users\Fachrul Ghiffari\AppData\Local\Temp\ipykernel_9948\3632284102.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df_median_jams_kota_bandung = df_median_jams_kota_bandung.drop('Unnamed: 0',1)

,time,kemendagri_kabupaten_kode,kemendagri_kabupaten_nama,street,level,median_length,median_delay,median_speed_kmh,total_records,id,date,median_level,geometry
0,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Jenderal Ahmad Yani,4,428.0,201.5,6.29,14,33471439,2022-07-06,4.0,"MULTILINESTRING ((107.622869 -6.919558, 107.62..."
1,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Cibaduyut Raya,5,24.0,-1.0,0.00,60,33471432,2022-07-06,5.0,"MULTILINESTRING ((107.59526 -6.947213, 107.595..."
2,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Cidurian Selatan,2,531.0,101.5,9.07,2,33471433,2022-07-06,2.0,"LINESTRING (107.652971 -6.940132, 107.653181 -..."
3,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Dr Setiabudi,1,919.0,61.0,20.42,2,33471434,2022-07-06,1.0,"LINESTRING (107.593922 -6.866493, 107.5939 -6...."
4,2022-07-06 00:00:00.000,32.73,KOTA BANDUNG,Gerbang Tol Gede Bage,5,318.5,-1.0,0.00,120,33471435,2022-07-06,5.0,"MULTILINESTRING ((107.690448 -6.961397, 107.69..."

In [16]:
df_median_jams_kota_bandung.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301995 entries, 0 to 301994
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   time                       301995 non-null  object
 1   kemendagri_kabupaten_kode  301995 non-null  float64
 2   kemendagri_kabupaten_nama  301995 non-null  object
 3   street                     299552 non-null  object
 4   level                      301995 non-null  int64
 5   median_length              301995 non-null  float64
 6   median_delay               301995 non-null  float64
 7   median_speed_kmh           301995 non-null  float64
 8   total_records              301995 non-null  int64
 9   id                         301995 non-null  int64
 10  date                       301995 non-null  object
 11  median_level               301995 non-null  float64
 12  geometry                   301995 non-null  object
dtypes: float64(5), int64(3), object(5)
memory usage: 30.0+ MB